== Instalacion de Arch Linux Base


Bibliografia : https://wiki.archlinux.org/title/installation_guide

=== Connect to thi Internet 
* Cable 

  recommended, you just have to plug in the cable

* Wifi 
red_wlan0 is the name of the wifi card, use $ip addr 

  root$ iwctl --passphrase  "password" station red_wlan0 connect wifi_name

=== Check boot mode(UEFI/BIOS) :

    root$ ls /sys/firmware/efi/efivars/

=== Mode UEFI
  
==== 3) Partition the disks 
  
for uefi boot it must be GPT type, if not:
  
  root$ change mbr a gpt

UEFI GPT :

    Mount :         Partition:	    Partition Type:       size:
    /mnt/boot/efi   /dev/sdX1		EFI system partition  260~512 MiB
    /mnt            /dev/sdX2		Linux x86-64 root (/) size > 20Gb
    [SWAP]          /dev/sdX3		Linux swap            same as ram size 

Format the partition :

* Linux /mnt

			root$ mkfs.ext4 /dev/sdXY

* UEFI /mnt/boot/efi:

			root$ mkfs.fat -F 32 /dev/sdXY

* swap

			root$ mkswap /dev/sdXY

Mount partitions :

* linux

  root$ mount /dev/sdXY /mnt

* EFI

  root$ mount /dev/sdXY /mnt/boot/efi

* swap

	root$ swapon /dev/sdXY

Go to standard configuration ... 

=== Mode DOS

for DOS boot it must be GPT type, if not:
  
  root$ change gpt to mbr

BIOS MBR :

		Mount:       Partition      partition type:     size:
		/mnt         /dev/sdX1		Linux               size > 20Gb
		[SWAP]       /dev/sdX2		Linux swap          same as ram size

Formatear prticiones :

* Linux /mnt

			root$ mkfs.ext4 /dev/sdXY

* swap

			root$ mkswap /dev/sdXY

Montar particiones :

* linux

  root$ mount /dev/sdXY /mnt

* swap

	root$ swapon /dev/sdXY

Go to standard configuration ... 

==== Packet Configuration

* necessary packages

	root$ pacstrap /mnt   base base-devel linux linux-firmware


* plain text editor for console ( vim , neovim , nano )

	$ pacstrap /mnt neovim

* internet program ( networkmanager )

	$ pacstrap /mnt networkmanager 

* other packages :

  sudo      -> super users adminitrator
  openssh   -> remote login client
  git       -> version controller

==== system configuration :

* fstab : partition file and mount

			root$ genfstab -U  /mnt >> /mnt/etc/fstab
			root$ cat /mnt/etc/fstab

* change to new system

			root$ arch-chroot /mnt 


==== language :

* to edite  /etc/locale.gen and  uncomment one language

                en_US.UTF-8 UTF-8  
                en_US ISO-8859-1  
			  root$ local-gen

* edite /etc/locale.conf 

        LANGUAGE=en_US.UTF-8
        LC_ALL=en_US.UTF-8
        LANG=en_US.UTF-8

* set keyboard language /etc/vconsole.conf

					KEYMAP=en

* for graphical environment or console emulator, this is temporary

    	root$ setxkbmap es
        root$ loadkeys es

==== time setting :
* time zone

			root$ ln -sf /usr/share/zoneinfo/Region/city /etc/localtime

* clock synchronization

			root$ hwclock --systohc

* if it doesn't work then:

  date --set "2022-04-03  13:51"
  hwclock --set --date=$(date +%D\ \%H:\%M\%S)

==== Network Configuration :
* name /etc/hostname

					nombredelequipo

* ip default /etc/hosts 

				127.0.0.1 localhost
				::1				localhost 
				127.0.1.1 nombredelequipo.localdomain nombredelequipo

==== root user configuration :
* password :

			root$ passwd

==== user configuration:

* create user :

  root$ useradd -m -g GroupUser nameUser
  root$ passwd nameUser

==== Instalar gestor de arranque( grub ) ;
	
* grub install:

  root$ pacmant -S grub os-prober efibootmgr

* create boot :
   
  root$ grub-install --target=x86_64-efi  --afi-directory=/boot/efi/  --bootloader-id=Arch_Linux
  root$ grub-mkconfig -o /boot/grub/grub.cfg


* end :
  
  root$ exit
  root$ reboot  
  or 
  root$ poweroff

==== Post Instalacion

* systemctl settings;

  root$ systemctl start NetworkManager
  root$ systemctl enable NetworkManager
  
  root$ systemctl start sshd
  root$ systemctl enable sshd

* sudo ( add users )

  root$ chmod +w /etc/sudoers
  edit /etc/sudoers :
  
  user ALL=(ALL:ALL) ALL

Installl Desktop ../InstallDesktop/
